version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "${DOCKER_HUB_USERNAME}/backend:${GIT_COMMIT_HASH}"
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://wasakodi79:hPzPt5nYwhO0TXBJ@cluster1.qv9fx.mongodb.net/ecommerce_db?retryWrites=true&w=majority&appName=Cluster1
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "${DOCKER_HUB_USERNAME}/frontend:${GIT_COMMIT_HASH}"
    container_name: frontend_container
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge