---
- name: Deploy E-Commerce Application to EC2
  hosts: all
  become: yes
  vars:
    ansible_ssh_timeout: 60
    app_dir: "/home/ubuntu/app"
    project_src: "{{ playbook_dir }}/.."  # Assumes playbook is in a subdirectory
    
  pre_tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: yes
      changed_when: false

  tasks:
    # Update packages and install dependencies
    - name: Update package cache
      apt:
        update_cache: yes
      retries: 3
      delay: 5
      until: true
      when: docker_check.rc != 0

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - rsync
        state: present
      retries: 3
      delay: 5
      until: true
      when: docker_check.rc != 0

    # Install Docker using the official Docker installation script
    - name: Install Docker using official script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker
      retries: 3
      delay: 5
      until: true
      when: docker_check.rc != 0

    # Install Docker Compose
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'
        force: yes
      retries: 3
      delay: 5
      until: true

    # Ensure Docker service is running
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      retries: 3
      delay: 5
      until: true

    # Create application directories
    - name: Create application directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu
      loop:
        - "{{ app_dir }}"
        - "{{ app_dir }}/backend"
        - "{{ app_dir }}/frontend"

    # Copy application files to EC2
    - name: Copy backend files
      synchronize:
        src: "{{ project_src }}/backend/"
        dest: "{{ app_dir }}/backend/"
        mode: push
        delete: yes  # Remove files on destination that are not on source
      become: no  # Run as the ansible user, not root

    - name: Copy frontend files
      synchronize:
        src: "{{ project_src }}/frontend/"
        dest: "{{ app_dir }}/frontend/"
        mode: push
        delete: yes
      become: no

    - name: Copy docker-compose file
      copy:
        src: "{{ project_src }}/docker-compose.yml"
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    # Clean up old Docker resources
    - name: Remove unused Docker data
      shell: docker system prune -af --volumes
      register: docker_prune
      changed_when: docker_prune.stdout.find('Total reclaimed space') != -1
      ignore_errors: yes

    # Deploy with Docker Compose
    - name: Deploy with Docker Compose
      shell: cd {{ app_dir }} && docker-compose down && docker-compose up -d
      args:
        chdir: "{{ app_dir }}"
      register: docker_compose_output
      changed_when: docker_compose_output.stdout.find('Creating') != -1 or docker_compose_output.stdout.find('Starting') != -1

    # Verify deployment
    - name: Check if containers are running
      shell: docker ps | grep -E 'frontend_container|backend_container'
      register: container_check
      changed_when: false
      ignore_errors: yes

    - name: Deployment status
      debug:
        msg: "Deployment successful! Containers are running."
      when: container_check.rc == 0

    - name: Deployment status
      fail:
        msg: "Deployment failed. Containers are not running properly."
      when: container_check.rc != 0